### ISSUE TITLE
[Feature Request] Advanced metrics support

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-dotnet#126]
### Describe the solution you'd like
With https://github.com/temporalio/sdk-core/pull/544 landed, we need to:

* [x] Support any missing prom options (done in #129)
* [x] Support any missing otel options (done in #129)
* ~Support user-accessible metric buffer-based forwarding~ (EDIT: Not needed with the below being present)
* [ ] Support .NET provided metric implementation (interesting...)
* [x] Support access to metrics from runtime (done in #129)
* [x] Support access to metrics from activity with default activity tags (done in #129)
* [x] Support access to metrics from workflow with default workflow tags and ignore metric updates during replay by default (done in #129)

**Comment by cretz** [comment]
Most of this is now done. The thing remaining, and it's non-trivial, is "Support .NET provided metric implementation".
